[masters]
DMS4-Prod-K8s-Master-01 ansible_host=10.10.10.11
DMS4-Prod-K8s-Master-02 ansible_host=10.10.10.12
DMS4-Prod-K8s-Master-03 ansible_host=10.10.10.13

[workers]
DMS4-Prod-K8s-Worker-01 ansible_host=10.10.10.21
DMS4-Prod-K8s-Worker-02 ansible_host=10.10.10.22
DMS4-Prod-K8s-Worker-03 ansible_host=10.10.10.23

[k8s_cluster:children]
masters
workers

[all:vars]
ansible_user=root
# Uncomment if you need to pin a specific SSH key file.
# ansible_ssh_private_key_file=/root/.ssh/id_ed25519
project_name=Data Management System 4
project_short_name=DMS4
environment_name=Prod
